# Generated by Django 5.2.18 on 2026-10-08 01:52

from django.db import migrations, models


def classify_existing_accounts(apps, schema_editor):
    Profile = apps.get_model('workflow', 'Profile')
    Profile.objects.using(schema_editor.connection.alias).filter(approved=False).update(department_confirmed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_stock_review_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(classify_existing_accounts, migrations.RunPython.noop),
    ]
