# Generated by Django 5.2.18 on 2026-10-08 04:48

from django.db import migrations, models


def format_existing_notices(apps, schema_editor):
    Notice = apps.get_model('workflow', 'Notice')
    Profile = apps.get_model('workflow', 'Profile')
    db = schema_editor.connection.alias
    ranks = dict(Profile.objects.using(db).values_list('user_id', 'rank'))
    labels = {'leave': '휴가원', 'office': '구매요청서', 'stock': '생산 재고 요청서'}
    rows = Notice.objects.using(db).filter(subject='', document__isnull=False).select_related('document__owner')
    for notice in rows.iterator():
        doc, text = notice.document, notice.text
        if '님의 검토 요청이 도착' in text:
            stage = '검토대기'
        elif '생산 재고 요청의 검토가 완료' in text or '발주대기로 전환' in text:
            stage = '검토완료'
        elif '검토가 완료되었습니다' in text:
            stage = '검토완료 · 승인대기'
        elif '최종 승인되었습니다' in text:
            stage = '승인완료'
        elif '기안이 반려되었습니다' in text:
            stage = '반려'
        elif '검토가 취소되었습니다' in text:
            stage = '검토취소'
        elif '최종 승인이 취소되었습니다' in text:
            stage = '승인취소'
        elif '구매·발주가 완료되었습니다' in text:
            stage = '배송중' if doc.kind == 'office' else '입고대기'
        elif '물품 수령이 확인되었습니다' in text:
            stage = '배송완료' if doc.kind == 'office' else '입고완료'
        elif '대기 중인 결재 담당자가 변경되었습니다' in text:
            stage = '담당자변경'
        else:
            continue
        notice.subject = f'{doc.owner.first_name or doc.owner.username} - {ranks.get(doc.owner_id, "직급 미지정")} - {labels.get(doc.kind, doc.kind)}'
        notice.stage = stage
        # Keep the original message, timestamp and read state unchanged.
        notice.save(using=db, update_fields=['subject', 'stage'])


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_accounting_read_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='stage',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notice',
            name='subject',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.RunPython(format_existing_notices, migrations.RunPython.noop),
    ]
